feat: add action onRelease: Create zip file from repo and send it as a zip …
plentymarkets/plentyshop-pwa pull request #122
Opened 2023-03-17 07:34 UTC by pfrincu-plenty

…file to the endpoint

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-04-19 07:00 UTC, Dominik2809 submitted a review, later dismissed

2023-04-19 08:01 UTC, ksted requested changes

2023-04-19 08:01 UTC, ksted commented on .github/workflows/release.yml
> +          name: zip-repository
```suggestion
          name: PWA
```
**chore**: Update name if updating above.

2023-04-19 08:01 UTC, ksted commented on .github/workflows/release.yml
> +          forms: '{ "tokenName":"${{ secrets.URL_ENDPOINT_TOKEN }}" }'
**question**: Sorin told me that sellers will only need one secret in the end. Why do we need two here?

2023-04-20 05:14 UTC, ksted commented
Actually, one more thing, can we call this workflow something other than "release"? I think "release" should be reserved for a workflow that actually creates a release.

This one could be called "upload", "publish", "deploy" or something to that effect.

2023-04-21 11:47 UTC, ksted approved these changes

2023-04-24 07:20 UTC, merged