feat: added loading animations where necessarry
plentymarkets/plentyshop-pwa pull request #138
Opened 2023-09-12 14:15 UTC by rbadici-plenty

## Why:

Closes: #ID

## Describe your changes

## Checklist before requesting a review
- [ ] My code follows the code style of this project.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-09-13 12:34 UTC, maxiroellplenty requested changes, later dismissed
The loading spinner should only be on the part of the page that is actually loading.
Also its missing, loading spinner for search.

2023-09-13 12:34 UTC, maxiroellplenty commented on apps/web/pages/category/[slug].vue
> +  <div class="relative" :class="{ 'pointer-events-none opacity-50': loading }">
loading spinner should only be on the product page not the whole page

2023-09-14 10:34 UTC, Tim-M-S commented
Changing the filters or sorting on the category page should only reload the item grid
![image](https://github.com/plentymarkets/plentyshop-pwa/assets/11943448/e4f89b90-aa57-4ae7-b00d-8df9550b6a23)

2023-09-14 10:43 UTC, Tim-M-S commented
Changing the shipping or payment provider should show a loader on both of them
<img width="859" alt="image" src="https://github.com/plentymarkets/plentyshop-pwa/assets/11943448/67318d42-384e-48b5-a6fd-40f0931fec8c">

2023-09-14 10:45 UTC, Tim-M-S commented
Switching between the tabs in the myaccount should show a loader in the changing section
<img width="1239" alt="image" src="https://github.com/plentymarkets/plentyshop-pwa/assets/11943448/83151b1b-4cb8-4d37-aea0-0b6791912e95">

2023-09-14 15:26 UTC, FabianGerke approved these changes

2023-09-14 15:26 UTC, merged