refactor: category tree interfaces
plentymarkets/plentyshop-pwa pull request #175
Opened 2023-04-24 14:14 UTC by maxiroellplenty

2023-04-25 08:56 UTC, ksted requested changes

2023-04-25 08:56 UTC, ksted commented on packages/composables/src/getters/categoryGetters.ts
> +  getCategoryDetails(category: Category)
```suggestion
  getCategoryName(category: Category): string,
  getCategoryDetails(category: Category): CategoryDetails | null
```
**todo**: Add return types.

2023-04-25 08:56 UTC, ksted commented on packages/api-client/src/types/category.ts
> +    plentyId: number
```suggestion
    canonicalLink: string
    categoryId: string
    description: string
    description2: string
    fulltext: string
    image: number
    imagePath: string
    image2: string
    image2Path: string
    itemListView: string
    lang: string
    metaDescription: string
    metaKeywords: string
    metaRobots: string
    metaTitle: string
    name: string
    nameUrl: string
    pageView: string
    plenty_category_details_image_path: string
    plenty_category_details_image2_path: string
    plentyId: number
    position: string
    shortDescription: string
    singleItemView: string
    updatedAt: string
    updatedBy: string
```
**suggestion**: Improve readability of long list by sorting the entries alphabetically. `image`, `image2`, `image2Path` and `imagePath` is an exception because of the logical connection.

As a side note, there's a [VSC extension](https://marketplace.visualstudio.com/items?itemName=zhihaocui.ts-interface-sorter) for automatically sorting interfaces.

2023-05-10 13:37 UTC, maxiroellplenty commented on packages/composables/src/getters/categoryTreeGetters.ts
> +// eslint-disable-next-line @typescript-eslint/no-unused-vars
done

2023-05-10 13:38 UTC, maxiroellplenty commented on packages/composables/src/getters/categoryTreeGetters.ts
> +    slug: getCategoryDetails(category.details)?.nameUrl || '',
done

2023-05-10 13:39 UTC, maxiroellplenty commented on packages/composables/src/getters/categoryGetters.ts
> +  getCategoryDetails(category: Category)
done

2023-05-10 13:42 UTC, maxiroellplenty commented on packages/api-client/src/types/category.ts
> +    plentyId: number
done

2023-05-10 13:49 UTC, ksted approved these changes

2023-05-10 13:58 UTC, merged