Feat/return component
plentymarkets/plentyshop-pwa pull request #190
Opened 2023-05-11 15:53 UTC by rbadici-plenty

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-05-24 18:05 UTC, maxiroellplenty commented
run: yarn lint --fix to fix linter issues

2023-05-24 18:21 UTC, maxiroellplenty requested changes

2023-05-24 18:21 UTC, maxiroellplenty commented on packages/api-client/src/api/getOrder/index.ts
> +export async function makeOrderReturn(context: Context, orderId: number, orderAccessKey:string, variationIds: object, returnNote: string): Promise<CreateReturnResponse> {
All the params should only be one object named params of type MakeOrderReturnParams that you have to create. This makes the code more readable.

2023-05-30 14:56 UTC, maxiroellplenty commented on packages/api-client/src/api/getOrder/index.ts
> +export async function makeOrderReturn(context: Context, orderId: number, orderAccessKey:string, variationIds: object, returnNote: string): Promise<CreateReturnResponse> {
did the changes

2023-06-05 18:14 UTC, maxiroellplenty submitted a review, later dismissed

2023-06-06 05:03 UTC, ksted requested changes
**todo**: Fix lint warnings.

2023-06-06 05:03 UTC, ksted commented on packages/composables/src/useMakeReturn/index.ts
> +    // Todo: Json to FormData mapping will be removed one the endpoint supports json payload
```suggestion
    // @TODO: Json to FormData mapping will be removed once the endpoint supports json payload
```

2023-06-06 06:41 UTC, ksted approved these changes

2023-06-06 07:54 UTC, merged