feat: subscribe newsletter
plentymarkets/plentyshop-pwa pull request #207
Opened 2023-05-24 09:43 UTC by FabianGerke

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-05-24 11:06 UTC, abocsan-plenty commented on packages/theme/lang/en.js
> +    'FormConfirmation': 'I hereby confirm that I have read and accept the <a href="#" class="sf-link">privacy policy</a>. I can revoke my consent at any time.',
Translation variables should be used for link. That way you don't have to go back to each language and change the url.

2023-05-24 11:06 UTC, abocsan-plenty commented on packages/theme/components/MyAccount/NewsletterSubscribeForm.vue
> +      <!--
Is the commented code still needed ?

2023-05-24 13:59 UTC, FabianGerke commented on packages/theme/lang/en.js
> +    'FormConfirmation': 'I hereby confirm that I have read and accept the <a href="#" class="sf-link">privacy policy</a>. I can revoke my consent at any time.',
@maxiroellplenty

2023-05-24 15:17 UTC, maxiroellplenty commented on packages/theme/components/MyAccount/NewsletterSubscribeForm.vue
> +      <!--
it is :D Tim wants it in some point in the future

2023-05-24 15:22 UTC, maxiroellplenty commented on packages/composables/src/useNewsletter/index.ts
> +        emailFolder: '10'
This should maybe be a param for the subscribe function so that you could subscribe to different newsletters in the templatew

2023-05-24 15:37 UTC, maxiroellplenty commented on packages/theme/components/MyAccount/NewsletterSubscribeForm.vue
> +    const emailAddress = ref('');
Maybe we could prefill the email address if you are already logged in? Could talk about that in the daily

2023-05-24 15:38 UTC, maxiroellplenty commented on packages/theme/components/MyAccount/NewsletterSubscribeForm.vue
> +  margin-top: 20px;
Replace what we can with tailwind?

2023-05-25 06:22 UTC, FabianGerke commented on packages/theme/lang/en.js
> +    'FormConfirmation': 'I hereby confirm that I have read and accept the <a href="#" class="sf-link">privacy policy</a>. I can revoke my consent at any time.',
Ah now I understand, yeah you guys are right

2023-05-25 08:18 UTC, FabianGerke commented on packages/theme/components/MyAccount/NewsletterSubscribeForm.vue
> +    const emailAddress = ref('');
Done.

2023-05-25 08:49 UTC, maxiroellplenty requested changes

2023-05-25 08:49 UTC, maxiroellplenty commented on packages/theme/components/MyAccount/NewsletterSubscribeForm.vue
> +.flex-names{
replace the scss with tailwind inside the template

2023-05-25 08:49 UTC, maxiroellplenty commented on packages/composables/src/useNewsletter/index.ts
> +  const subscribeNewsletter = async (email: string, firstName: string, lastName: string, emailFolder: string): Promise<void> => {
use one params object of type NewsletterSubscriptionParams to make it more readable

2023-05-25 10:27 UTC, maxiroellplenty approved these changes

2023-05-25 12:40 UTC, merged