fix: shipping provider error when selected
plentymarkets/plentyshop-pwa pull request #215
Opened 2023-05-31 12:46 UTC by abocsan-plenty

## Description

2023-05-31 14:26 UTC, maxiroellplenty submitted a review, later dismissed

2023-05-31 15:48 UTC, ksted requested changes

2023-05-31 15:48 UTC, ksted commented on packages/api-client/src/api/getPaymentProvider/index.ts
> +  const url: URL = new URL('/rest/storefront/checkout/payment/', context.config.api.url);
**todo**: Fix lint

2023-06-01 05:14 UTC, ksted approved these changes

2023-06-01 05:40 UTC, merged