Pp readonly
plentymarkets/plentyshop-pwa pull request #222
Opened 2023-06-07 11:29 UTC by rbadici-plenty

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-06-07 14:02 UTC, maxiroellplenty requested changes
<img width="1514" alt="Bildschirmfoto 2023-06-07 um 15 52 02" src="https://github.com/plentymarkets/plentyshop-pwa/assets/30629157/940f6486-0a77-4acf-84c3-7f052114c5dc">

2023-06-09 15:53 UTC, rbedeoan-plenty commented
subtasks left:
-default billing page
-ui layout

2023-06-12 06:25 UTC, rbedeoan-plenty commented
shipping providers should have a image,
currently hardcoded string in getShippingMethodImage

2023-06-13 15:07 UTC, maxiroellplenty requested changes

2023-06-15 09:33 UTC, maxiroellplenty approved these changes

2023-06-15 09:33 UTC, merged