feat: base price on category
plentymarkets/plentyshop-pwa pull request #238
Opened 2023-06-27 12:38 UTC by rbedeoan-plenty

https://dev.azure.com/plentymarkets/plentymarkets/_sprints/backlog/BD%20-%20Team%20-%20LM/plentymarkets/Areas/Sprint%2033?workitem=63854

2023-06-27 12:52 UTC, rbedeoan-plenty commented
we should use product getters from productGetters not cartGetters...

2023-06-27 13:12 UTC, rbedeoan-plenty commented
@maxiroellplenty 
2 questions
1.are you sure about this request: 
"Try to unify changes by having reusable components (LTS uses the same item-component for basket-preview, Basket and checkout >> basketListItem.vue" 
Both files in which cart product list is used have diferent ways of displaying the product list (table style..)
2.should't we use getter function only from productGetters when whe display product fields? (for a new dev that interacts with the app seems more straight forward..)

2023-06-28 13:12 UTC, rbedeoan-plenty commented
currently failing paypal e2e,i think it does't have to do with changes in current branch

2023-06-29 14:51 UTC, FabianGerke commented on packages/theme/components/BasePrice.vue
Is there a way just to give the product-prop to the component?

2023-06-29 14:52 UTC, FabianGerke commented on packages/theme/components/CartSidebar.vue
Not really consistent

2023-06-29 14:55 UTC, FabianGerke requested changes

2023-06-29 14:55 UTC, FabianGerke commented on packages/theme/pages/Product.vue
Maybe we can do it like:

<BasePrice :product="product" class="baseprice-online" />

?

2023-06-29 14:55 UTC, FabianGerke commented on packages/theme/components/BasePrice.vue
Use getUnitContent instead of getUnitId

2023-06-29 14:55 UTC, FabianGerke commented on packages/theme/components/BasePrice.vue
> +<style scoped>
Remove some css with tailwind

2023-07-03 07:52 UTC, rbedeoan-plenty commented on packages/theme/components/BasePrice.vue
> +      type: Boolean,
need some context

2023-07-03 08:24 UTC, FabianGerke submitted a review, later dismissed

2023-07-03 08:28 UTC, FabianGerke approved these changes

2023-07-03 08:42 UTC, merged