feat: own useUser composable
plentymarkets/plentyshop-pwa pull request #240
Opened 2023-06-28 14:49 UTC by FabianGerke

## Why:
To have a "isGuest"-flag

Closes: 

## Describe your changes

## Checklist before requesting a review
- [ ] My code follows the code style of this project.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-06-29 10:43 UTC, rbedeoan-plenty commented on packages/composables/src/useUser/index.ts
> +      isGuest.value = true;
what happens if request   await context.$plentymarkets.api.loginAsGuest(params.email);  fails ?
should we check for fail case ? or always give it true ? (isGuest.value = true;)

2023-06-29 10:56 UTC, rbedeoan-plenty requested changes
all ok, maybe check if backend call fails ?

2023-06-29 13:15 UTC, FabianGerke commented on packages/composables/src/useUser/index.ts
> +      isGuest.value = true;
You are right, I will add this.

2023-07-03 08:21 UTC, rbedeoan-plenty approved these changes

2023-07-03 08:25 UTC, merged