feat: show properties cart
plentymarkets/plentyshop-pwa pull request #285
Opened 2024-01-05 09:28 UTC by FabianGerke

## Why:

Closes: AB#90293

## Describe your changes

## Checklist before requesting a review

- [ ] My code follows the code style of this project.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I've updated `docs/changelog/changelog_en.md` and `docs/changelog/changelog_de.md`. If I'm a non-German speaker, I've still updated the file with the English version as a placeholder.

2024-01-08 17:31 UTC, maxiroellplenty requested changes

2024-01-08 17:31 UTC, maxiroellplenty commented on apps/web/components/CartOrderProperty/CartOrderProperty.vue
> +    <span v-if="productPropertyGetters.getOrderPropertyValueType(property) !== 'empty'">: {{ value }}</span>
!isOrderPropertyCheckbox(property)

2024-01-08 17:31 UTC, maxiroellplenty commented on apps/web/components/CartPageContent/CartPageContent.vue
> +      <client-only>
why?

2024-01-08 17:31 UTC, maxiroellplenty commented on apps/web/components/OrderSummary/OrderSummary.vue
> +        </div>
could use getters

2024-01-08 19:20 UTC, FabianGerke commented on apps/web/components/CartOrderProperty/CartOrderProperty.vue
> +    <span v-if="productPropertyGetters.getOrderPropertyValueType(property) !== 'empty'">: {{ value }}</span>
Smart

2024-01-09 12:54 UTC, maxiroellplenty approved these changes

2024-01-09 12:54 UTC, merged