fix: validation for return quantity and reason
plentymarkets/plentyshop-pwa pull request #325
Opened 2024-02-06 15:19 UTC by rbedeoan-plenty

AB#92286

2024-02-06 15:19 UTC, plenty-to-azure commented
✅ Successfully linked to Azure Boards work item(s):
- [Product Backlog Item 92286](https://dev.azure.com/plentymarkets/0af57df9-8662-4901-bb97-8e88b07ff0c9/_workitems/edit/92286)

2024-02-08 09:58 UTC, maxiroellplenty requested changes

2024-02-08 09:58 UTC, maxiroellplenty commented on apps/web/components/OrderReturnForm/OrderReturnForm.vue
> +const quantitySelected = computed(() =>
can we move this code into the composable?

2024-02-08 09:58 UTC, maxiroellplenty commented on apps/web/components/OrderReturnForm/OrderReturnForm.vue
> +const hasQuantityAndNoReasonsSelected = computed(() =>
this check could also be handled in the composable

2024-02-08 16:38 UTC, maxiroellplenty requested changes

2024-02-08 16:38 UTC, maxiroellplenty commented on apps/web/nuxt.config.ts
> +      validateReturnReasons: process.env.VALIDATE_RETURN_REASONS === '1' ?? false,
Add VALIDATE_RETURN_REASONS value to the .env.example

2024-02-09 08:46 UTC, maxiroellplenty approved these changes

2024-02-09 08:46 UTC, merged