feat: image attribute & feedback changes
plentymarkets/plentyshop-pwa pull request #347
Opened 2024-03-05 11:04 UTC by FabianGerke

## Why:

Closes: AB#98852
Part of AB#95659

## Describe your changes

## Checklist before requesting a review

- [ ] My code follows the code style of this project.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I've updated `docs/changelog/changelog_en.md` and `docs/changelog/changelog_de.md`. If I'm a non-German speaker, I've still updated the file with the English version as a placeholder.

2024-03-07 18:01 UTC, maxiroellplenty requested changes

2024-03-07 18:01 UTC, maxiroellplenty commented on apps/web/components/ProductAttributes/AttributeImage/AttributeImage.vue
> +const getImagePath = (item: VariationMapProductAttributeValue): string => {
I guess this should make use of the webp composable. So that in the future the image comes with modern fromats.

2024-03-08 10:09 UTC, FabianGerke commented on apps/web/components/ProductAttributes/AttributeImage/AttributeImage.vue
> +const getImagePath = (item: VariationMapProductAttributeValue): string => {
I think there is no webp conversion for that kind of images.

2024-03-08 10:24 UTC, maxiroellplenty approved these changes

2024-03-08 10:24 UTC, merged