feat: add category filter composable
plentymarkets/plentyshop-pwa pull request #35
Opened 2023-08-08 15:23 UTC by ksted

AB#70300

2023-08-08 15:35 UTC, FabianGerke requested changes

2023-08-08 15:35 UTC, FabianGerke commented on apps/web/composables/useCategoryFilter/types.ts
> +  getCatLink(category: AgnosticCategoryTree): string;
Use "CategoryTreeItem" instead of "AgnosticCategoryTree", we are away from the "AgnosticCategoryTree".

2023-08-08 15:35 UTC, FabianGerke commented on apps/web/composables/useCategoryFilter/useCategoryFilter.ts
> +};
Maybe can be removed because we have the "categoryTreeGetters.getSlug(category)"?

2023-08-08 16:03 UTC, maxiroellplenty commented on apps/web/composables/useCategoryFilter/useCategoryFilter.ts
> +const defaultItemsPerPage = 20;
Andrei just added default values to useProducts for itemsPerPage and default. We should find a place for both composables.

2023-08-09 11:06 UTC, abocsan-plenty approved these changes

2023-08-09 11:24 UTC, merged