feat: changed reviews text and on click behaviour
plentymarkets/plentyshop-pwa pull request #37
Opened 2023-08-09 07:51 UTC by rbadici-plenty

2023-08-09 08:03 UTC, FabianGerke requested changes
Fix the lint errors first
Command: yarn lint

2023-08-09 10:13 UTC, FabianGerke requested changes
Maybe also an idea to open the review accordion when clicking on "Show all reviews"?
@maxiroellplenty

2023-08-09 10:13 UTC, FabianGerke commented on apps/web/components/ui/PurchaseCard/PurchaseCard.vue
> +        {{ $t('showAllReviews') }}
Why not using the smooth solution from the pwa?

`const scrollToReviews = () => {
      document
        .getElementById('customerReviewsAccordion')
        .scrollIntoView({ behavior: 'smooth', block: 'start', inline: 'nearest' });
    };`

2023-08-15 10:50 UTC, ksted commented on apps/web/components/ui/PurchaseCard/PurchaseCard.vue
> +  openReviewsAccordion();
**todo**: Check if already open

2023-08-15 18:13 UTC, maxiroellplenty approved these changes

2023-08-16 05:13 UTC, merged