feat: quick checkout design work
plentymarkets/plentyshop-pwa pull request #403
Opened 2024-04-09 06:38 UTC by abocsan-plenty

## Why:

Closes: #ID

## Describe your changes

## Checklist before requesting a review

- [ ] My code follows the code style of this project.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I've updated `docs/changelog/changelog_en.md` and `docs/changelog/changelog_de.md`. If I'm a non-German speaker, I've still updated the file with the English version as a placeholder.

2024-04-16 13:19 UTC, maxiroellplenty requested changes

2024-04-16 13:19 UTC, maxiroellplenty commented on apps/web/nuxt.config.ts
> +      enableQuickCheckoutTimer: true,
we could already use an env var for that

2024-04-16 13:19 UTC, maxiroellplenty commented on apps/web/components/QuickCheckout/QuickCheckout.vue
> +        <span v-if="timer && config.public.enableQuickCheckoutTimer" class="mr-2 text-gray-400">{{ timer }}s</span>
`config.public.enableQuickCheckoutTimer` can we have this info in the composable?

2024-04-16 13:19 UTC, maxiroellplenty commented on apps/web/components/QuickCheckout/QuickCheckout.vue
> +        <NuxtImg
this should use `addModernImageExtension` from `useModernImage` to load modern image formats

2024-04-16 13:19 UTC, maxiroellplenty commented on apps/web/lang/en.json
> +    "cartContains": "Your cart contains {count} item | Your cart contains {count} items",
how does that work with the `|`

2024-04-16 13:28 UTC, abocsan-plenty commented on apps/web/lang/en.json
> +    "cartContains": "Your cart contains {count} item | Your cart contains {count} items",
i18n automatically detects pluralization via the pipe character. Left is if it detects 1, right is if it detects > 1.

https://vue-i18n.intlify.dev/guide/essentials/pluralization.html

@maxiroellplenty

2024-04-16 16:09 UTC, maxiroellplenty submitted a review, later dismissed

2024-05-02 08:02 UTC, maxiroellplenty approved these changes

2024-05-02 08:03 UTC, merged