feat: feedback component
plentymarkets/plentyshop-pwa pull request #437
Opened 2024-04-30 13:06 UTC by luisaha

## Why:

Closes: #ID

## Describe your changes

## Checklist before requesting a review

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] I've updated `docs/changelog/changelog_en.md` and `docs/changelog/changelog_de.md`. If I'm a non-German speaker, I've still updated the file with the English version as a placeholder.

2024-05-08 16:40 UTC, fmutschler requested changes, later dismissed

2024-05-08 16:40 UTC, fmutschler commented on apps/web/lang/de.json
> +    "createReviewFormTitle": "Schreib eine Bewertung",
Hier benutzt du den Imperativ "Schreib"; Die meisten Anweisungen sind allerdings im infinitiv verfasst. Konsequent wäre hier also "Bewertung schreiben". 
Dazu können wir gerne noch Rücksprache halten.

2024-05-08 16:40 UTC, fmutschler commented on apps/web/lang/de.json
> +    "yourAnswer": "Ihre Antwort",
Ist die formale Anrede hier richtig?
Sonst wird im PR immer geduzt.

2024-05-08 16:40 UTC, fmutschler commented on apps/web/lang/de.json
> +    "deleteReview": "Bewertung Löschen?",
"Löschen" mit lowercase l

2024-05-08 16:40 UTC, fmutschler commented on apps/web/lang/de.json
> +      "textareaMaxLength": "Die maximal zulässige Länge beträgt 500 Zeichen"
Satzzeichen (Punkt) ergänzen)

2024-05-08 16:40 UTC, fmutschler commented on apps/web/lang/de.json
> +      "ratingRequired": "Füge Dein Rating hinzu",
Wann wird "Rating" verwendet und wann "Bewertung"?

2024-05-08 16:40 UTC, fmutschler commented on apps/web/lang/en.json
> +  "createCustomerReview": "Bewertung abgeben",
EN?

2024-05-08 16:40 UTC, fmutschler commented on apps/web/lang/en.json
> +    "saveAnswer": "Submit Answer",
"answer" sollte lowercase sein

2024-05-08 16:40 UTC, fmutschler commented on apps/web/lang/en.json
> +    "deleteReview": "Delete  Review?",
Review sollte lowercase sein; zusätzliches Leerzeichen entfernen

2024-05-08 16:40 UTC, fmutschler commented on apps/web/lang/en.json
> +    "deleteAnswer": "Delete  Answer?",
Answer sollte lowercase sein; zusätzliches Leerzeichen entfernen

2024-05-08 16:40 UTC, fmutschler commented on apps/web/lang/en.json
> +      "textareaMaxLength": "Maximum allowed lenght is 500"
Typo bei "length"; "characters" sollte nach 500 noch ergänzt werden

2024-05-08 16:40 UTC, fmutschler commented on docs/changelog/changelog_en.md
> +- product reviews on single item pages
Product sollte uppercase sein am Satzbeginn

2024-05-10 10:52 UTC, Tim-M-S commented on apps/web/lang/de.json
> +    "yourAnswer": "Ihre Antwort",
@fmutschler Please check the rest of the translations. I think we use the formal form everywhere else

2024-05-14 07:18 UTC, maxiroellplenty approved these changes

2024-05-14 07:20 UTC, merged