fix: bundle items accessability
plentymarkets/plentyshop-pwa pull request #449
Opened 2024-05-13 11:21 UTC by N-Feist

[AB#106174]

## Why:

Closes: #ID

## Describe your changes

## Checklist before requesting a review

- [ ] My code follows the code style of this project.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I've updated `docs/changelog/changelog_en.md` and `docs/changelog/changelog_de.md`. If I'm a non-German speaker, I've still updated the file with the English version as a placeholder.

2024-05-13 11:56 UTC, FabianGerke requested changes

2024-05-13 11:56 UTC, FabianGerke commented on apps/web/components/BundleOrderItems/BundleOrderItems.vue
> +}
```suggestion
const isLinkable = (item: ProductBundleComponent): boolean => {
  return productBundleGetters.isItemBundleSalable(item) && !productBundleGetters.getBundleItemUrl(item).includes('null');
}
```
Shorter solution but you have to check lint too.

2024-05-17 09:15 UTC, rbedeoan-plenty requested changes
if product url does not contain category, or valid path user may be provided with wrong url. Validation that user is provided with valid destination should be done in backend or frontend.

2024-05-22 08:08 UTC, FabianGerke approved these changes

2024-05-23 09:20 UTC, rbedeoan-plenty approved these changes

2024-05-23 09:31 UTC, merged