feat: Fetching PWA settings / creating .env file on before build hook
plentymarkets/plentyshop-pwa pull request #544
Opened 2024-07-02 13:41 UTC by clincu-plenty

## Why:

Closes: #ID

## Describe your changes

## Checklist before requesting a review

- [ ] My code follows the code style of this project.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I've updated `docs/changelog/changelog_en.md` and `docs/changelog/changelog_de.md`. If I'm a non-German speaker, I've still updated the file with the English version as a placeholder.

2024-07-02 15:35 UTC, maxiroellplenty requested changes

2024-07-02 15:35 UTC, maxiroellplenty commented on apps/web/.eslintignore
> +utils/configurationHelper.ts
please remove and disable specific rules if necessary.

2024-07-02 15:35 UTC, maxiroellplenty commented on apps/web/utils/configurationHelper.ts
> +// read .env file & convert to array
We usually don't write comments in the app, if the code is complex we move it into a function and explain what the code does by having a descriptive function name.

2024-07-02 15:35 UTC, maxiroellplenty commented on apps/web/utils/configurationHelper.ts
> +  console.log('Creating .env.tmp file...');
I would only have one console log that confirms writing the env file.
And only log errors and use some tryCatch around the operations.

2024-07-04 12:58 UTC, ksted submitted a review, later dismissed

2024-07-04 13:25 UTC, maxiroellplenty approved these changes, later dismissed

2024-07-04 16:18 UTC, clincu-plenty commented on apps/web/build/fetchConfiguration.ts
> +  await fetchAndWriteRemoteConfiguration();
Lint threw this error. Had to fix it.

2024-07-04 16:20 UTC, clincu-plenty commented on apps/web/build/fetchConfiguration.ts
> +  if (environmentMap.DISABLE_SETTINGS_FETCH === undefined || environmentMap.DISABLE_SETTINGS_FETCH === '1') {
Fixing both cases, first case datatype is undefined not 'undefined' as string.
Second case, when the DISABLE_SETTINGS_FETCH is true => No fetching, so we throw the warn.

2024-07-04 16:20 UTC, clincu-plenty commented on apps/web/build/fetchConfiguration.ts
> +    if (key === 'DISABLE_SETTINGS_FETCH') continue;
I think this might be a better solution? Looks better from my POV.

2024-07-05 05:18 UTC, ksted approved these changes

2024-07-05 05:18 UTC, merged