fix: preload logo
plentymarkets/plentyshop-pwa pull request #596
Opened 2024-08-08 10:44 UTC by rbedeoan-plenty

AB#118858

2024-08-12 06:34 UTC, ivladu-plenty submitted a review, later dismissed

2024-08-12 09:43 UTC, maxiroellplenty requested changes

2024-08-12 09:43 UTC, maxiroellplenty commented on docs/changelog/changelog_en.md
> +- Logo image is preloaded not lazyloaded.
```suggestion
-  Shop logo is now preloaded.
```

2024-08-14 06:53 UTC, abocsan-plenty approved these changes

2024-08-14 07:37 UTC, maxiroellplenty approved these changes

2024-08-14 07:37 UTC, merged