Feat/terms and conditions
plentymarkets/plentyshop-pwa pull request #67
Opened 2023-08-22 10:58 UTC by rbadici-plenty

## Why:

Closes: #ID

## Describe your changes

## Checklist before requesting a review
- [ ] My code follows the code style of this project.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-08-22 17:45 UTC, maxiroellplenty requested changes

2023-08-22 17:45 UTC, maxiroellplenty commented on apps/web/pages/Unsubscribe.vue
> +export default {
also this has to be script setup from compositon api not options api

2023-08-23 08:52 UTC, FabianGerke requested changes
Remove css and use tailwind in all your components.

2023-08-23 08:52 UTC, FabianGerke commented on apps/web/pages/CancellationForm.vue
> +}
Remove css and use the class p-5 instead.
https://tailwindcss.com/docs/padding

2023-08-23 08:52 UTC, FabianGerke commented on apps/web/pages/CancellationForm.vue
> +  <div class="legal-texts" v-html="getHTMLTexts()" />
replace legal-texts with p-5

2023-08-24 05:47 UTC, ksted requested changes

2023-08-24 05:47 UTC, ksted commented on apps/web/composables/useLegalInformation/useLegalInformation.ts
> +   */
```suggestion
  /**
   * @description Function for legal information of the given type.
   * @param LegalTextsParams Type of the legal information
   * @example
   * getLegalTexts({type: 'CancellationForm',});
   * @example
   * getLegalTexts({type: 'CancellationRights',});
   * @example
   * getLegalTexts({type: 'LegalDisclosure',});
   * @example
   * getLegalTexts({type: 'PrivacyPolicy',});
   * @example
   * getLegalTexts({type: 'TermsConditions',});
   */
```

2023-08-24 05:47 UTC, ksted commented on apps/web/lang/en.json
> +      }
```suggestion
    "legal": {
      "label": "Legal",
      "subcategories": {
        "cancellationForm": "Cancellation form",
        "cancellationRights": "Cancellation rights",
        "legalDisclosure": "Legal disclosure",
        "privacyPolicy": "Privacy policy",
        "termsAndConditions": "Terms and conditions",
      }
```
**todo**: Also add translations to `de.json`.
```
    "legal": {
      "label": "Rechtliches",
      "subcategories": {
        "cancellationForm": "Widerrufsformular",
        "cancellationRights": "Widerrufsbelehrung",
        "legalDisclosure": "Impressum",
        "privacyPolicy": "Datenschutzerklärung",
        "termsAndConditions": "AGB"
      }
```

2023-08-24 06:00 UTC, ksted commented
**todo**: Please also add the links to the terms and conditions and to the privacy policy in the checkout.
<img width="855" alt="Screenshot 2023-08-24 at 07 59 49" src="https://github.com/plentymarkets/storefront-nuxt3-boilerplate/assets/43753494/98c4dc3f-851a-4ec3-b027-848fa96b9a9d">

2023-08-24 09:36 UTC, ksted approved these changes

2023-08-24 09:49 UTC, FabianGerke approved these changes

2023-08-24 12:38 UTC, ksted approved these changes

2023-08-24 12:38 UTC, merged