feat: adding alt property to hero banner
plentymarkets/plentyshop-pwa pull request #743
Opened 2024-10-17 07:39 UTC by clincu-plenty

## Why:

Closes: #ID

## Describe your changes

## Checklist before requesting a review

- [ ] My code follows the code style of this project.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I've updated `docs/changelog/changelog_en.md` and `docs/changelog/changelog_de.md`. If I'm a non-German speaker, I've still updated the file with the English version as a placeholder.

2024-10-17 07:53 UTC, aoltean-plenty approved these changes, later dismissed

2024-10-18 05:36 UTC, ksted requested changes
**issue**: The MediaCard also uses CDN images and should get the same treatment as the Hero.

2024-10-18 05:36 UTC, ksted commented on apps/web/components/ui/HeroCarousel/types.ts
> +  alt: string;
**question**: When we bring back the different image sizes, our `image` property will look like this, right?

```
image: {
  lg: string,
  md: string,
  sm: string
}
```
Should `alt` also become part of `image` then?

2024-10-18 10:42 UTC, ksted approved these changes

2024-10-24 09:12 UTC, clincu-plenty commented
Closing this one here because I created another branch to resolve all conflicts we had here.
This is the new PR: https://github.com/plentymarkets/plentyshop-pwa/pull/758

2024-10-24 09:12 UTC, closed without merging