New Toolbar component
plentymarkets/plentyshop-pwa pull request #763
Opened 2024-10-28 14:41 UTC by aoltean-plenty

## Why:

Closes: #ID

## Describe your changes

## Checklist before requesting a review

- [ ] My code follows the code style of this project.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I've updated `docs/changelog/changelog_en.md` and `docs/changelog/changelog_de.md`. If I'm a non-German speaker, I've still updated the file with the English version as a placeholder.

2024-10-31 11:10 UTC, ksted requested changes

2024-10-31 11:10 UTC, ksted commented on apps/web/components/Editor/Editor.vue
> +        placeholder="Edit JSON here..."
**issue**: Please use translation keys (`$t`) throughout.

2024-10-31 11:59 UTC, ksted commented on apps/web/lang/de.json
> +    "editJsonPlaceholder": "Bearbeiten Sie JSON hier..."
```suggestion
    "publish": "Veröffentlichen",
    "stopEdit": "Abbrechen",
    "formatJson": "Template formatieren",
    "minifyJson": "Template minimieren",
    "clearJson": "Template löschen",
    "editJsonPlaceholder": "JSON-Template eingeben..."
```

2024-10-31 11:59 UTC, ksted commented on apps/web/lang/en.json
> +   "editJsonPlaceholder": "Edit JSON here..."
```suggestion
    "stopEdit": "Cancel",
    "formatJson": "Format template",
    "minifyJson": "Minify template",
    "clearJson": "Clear template",
   "editJsonPlaceholder": "Enter JSON template..."
```

2024-10-31 12:09 UTC, oivan-plenty approved these changes

2024-10-31 12:12 UTC, clincu-plenty approved these changes

2024-11-01 11:22 UTC, ksted approved these changes

2024-11-01 11:27 UTC, merged