chore: version 1.8.0
plentymarkets/plentyshop-pwa pull request #886
Opened 2024-12-11 07:45 UTC by ksted

## Why:

Version 1.8.0 release.

## Describe your changes

- Updates the changelog.

## Checklist before requesting a review

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] I've updated `docs/changelog/changelog_en.md` and `docs/changelog/changelog_de.md`. If I'm a non-German speaker, I've still updated the file with the English version as a placeholder.

2024-12-12 18:39 UTC, Tim-M-S requested changes

2024-12-12 18:39 UTC, Tim-M-S commented on docs/changelog/changelog_en.md
> +- The order of attribute select and order properties on product pages have been switched to better reflect the user flow.
```suggestion
- The order of attribute select and order properties on product pages have been switched to better reflect the user flow.
- The values of the attributes are now sorted in descending order by position, then by id and then alphabetically  
```

2024-12-12 18:39 UTC, Tim-M-S commented on docs/changelog/changelog_en.md
> +## v1.8.0 (2024-12-11)
```suggestion
## v1.8.0 (2024-12-13)
```

2024-12-12 18:39 UTC, Tim-M-S commented on docs/changelog/changelog_en.md
> +- Fixed an issue causing the Login modal to be unresponsive in the user interface.
```suggestion
- Fixed an issue causing the login modal to be unresponsive in the user interface.
```

2024-12-13 06:13 UTC, ksted commented on docs/changelog/changelog_en.md
> +- The order of attribute select and order properties on product pages have been switched to better reflect the user flow.
```suggestion
- The order of attribute select and order properties on product pages have been switched to better reflect the user flow.
- The values of attributes are now sorted in descending order by position, then by ID and then alphabetically.
```

2024-12-13 11:39 UTC, Tim-M-S approved these changes

2024-12-13 13:17 UTC, merged